/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inicio;

// son los import nesesarios eee
import Conexion_base_de_datos.Conexion;
import inicio.AltasAsignaturas;
import inicio.AltasCuatrimestre;
import inicio.AsignarAsignatura;
import inicio.Docentes;
import inicio.EliminarAsignaturas;
import inicio.HorariosAlumnos;
import inicio.HorariosExternos;
import inicio.IngresaralSistema;
import inicio.PaginaPrincipalGeneraciondeHorarios;
import inicio.Usuarios;
import inicio.cuatrimestres;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 
 */
public class ModificarAsignaturas extends javax.swing.JFrame {
 
    /**
     * Creates new form INTERFAZ
     */
    public ModificarAsignaturas() {
        initComponents();
        mostrardatosmodificar();
        setResizable(false);
        setSize(1300,648);
        setTitle("Modificar asignatura");
    }
     void mostrardatosmodificar(){
                 
       modelomodificar = new DefaultTableModel();
       modelomodificar.addColumn("ID");
       modelomodificar.addColumn("Nombre");
       modelomodificar.addColumn("Clave");
       modelomodificar.addColumn("creditos");
       modelomodificar.addColumn("horas");
       modelomodificar.addColumn("Cuatrimestre");
       
           
            String sqlmodificar = "SELECT *FROM asignatura WHERE cuatrimestre_id LIKE '%" + buscarmodificarr.getText() + "%' "
                    + "OR nombre LIKE '%" + buscarmodificarr.getText() + "%'"
                    + "OR clave LIKE '%" + buscarmodificarr.getText() + "%'"
                    + "OR creditos LIKE '%" + buscarmodificarr.getText() + "%'"
                    + "OR horas LIKE '%" + buscarmodificarr.getText() + "%'";
        
        tablamodificarasignaturas.setModel(modelomodificar);
        String []datos = new String [10];
        try{
        Statement st = con2.createStatement();
        ResultSet rs= st.executeQuery(sqlmodificar);
        while (rs.next()){
        datos [0]=rs.getString(1);
        datos [1]=rs.getString(2);
        datos [2]=rs.getString(3);
        datos [3]=rs.getString(4);
        datos [4]=rs.getString(5);
        datos [5]=rs.getString(6);
        
        
         modelomodificar.addRow(datos);
        tablamodificarasignaturas.setModel(modelomodificar);
}
    }catch (Exception e){
       //  Logger.getLogger(consultadocentes.class.getName()).log(Level.SEVERE, null, ex); 
        System.out.println("chupando faros" + e);
    }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cuatrimestre = new javax.swing.JButton();
        Docentes = new javax.swing.JButton();
        HorariosExternos = new javax.swing.JButton();
        HorariosAlumnos = new javax.swing.JButton();
        Usuarios = new javax.swing.JButton();
        GeneraciondeHorarios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        SGH = new javax.swing.JLabel();
        LogoUnipoli = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JButton();
        NombredelUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AsignarMaterias = new javax.swing.JButton();
        AltasdeUsuarios = new javax.swing.JButton();
        AsignaciondePrivilegios = new javax.swing.JButton();
        ModificaciondeUsuarios = new javax.swing.JButton();
        ConsultarUsuarios = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AltaGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablamodificarasignaturas = new javax.swing.JTable();
        botonguardarcambio = new javax.swing.JButton();
        campoid = new javax.swing.JTextField();
        Id = new javax.swing.JLabel();
        nombremodificar = new javax.swing.JTextField();
        Id1 = new javax.swing.JLabel();
        creditosmodificar = new javax.swing.JTextField();
        clavemodificar = new javax.swing.JTextField();
        horasmodificar = new javax.swing.JTextField();
        Id2 = new javax.swing.JLabel();
        Creditos = new javax.swing.JLabel();
        Creditos1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        try {
            buscarmodificarr =(javax.swing.JTextField)java.beans.Beans.instantiate(getClass().getClassLoader(), "inicio.ModificarAsignaturas_buscarmodificarr");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        Creditos2 = new javax.swing.JLabel();
        cuatrimestremodificarasignatura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        Cuatrimestre.setBackground(new java.awt.Color(255, 102, 0));
        Cuatrimestre.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Cuatrimestre.setText("Cuatrimestre");
        Cuatrimestre.setAlignmentX(0.1F);
        Cuatrimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuatrimestreActionPerformed(evt);
            }
        });
        getContentPane().add(Cuatrimestre);
        Cuatrimestre.setBounds(68, 93, 120, 25);

        Docentes.setBackground(new java.awt.Color(255, 102, 0));
        Docentes.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Docentes.setText("Docentes");
        Docentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocentesActionPerformed(evt);
            }
        });
        getContentPane().add(Docentes);
        Docentes.setBounds(216, 93, 104, 25);

        HorariosExternos.setBackground(new java.awt.Color(255, 102, 0));
        HorariosExternos.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        HorariosExternos.setText("Horarios Externos");
        HorariosExternos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariosExternosActionPerformed(evt);
            }
        });
        getContentPane().add(HorariosExternos);
        HorariosExternos.setBounds(370, 93, 141, 25);

        HorariosAlumnos.setBackground(new java.awt.Color(255, 102, 0));
        HorariosAlumnos.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        HorariosAlumnos.setText("Horarios Alumnos");
        HorariosAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariosAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(HorariosAlumnos);
        HorariosAlumnos.setBounds(563, 93, 148, 25);

        Usuarios.setBackground(new java.awt.Color(255, 102, 0));
        Usuarios.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Usuarios.setText("Usuarios");
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(Usuarios);
        Usuarios.setBounds(934, 93, 93, 25);

        GeneraciondeHorarios.setBackground(new java.awt.Color(255, 102, 102));
        GeneraciondeHorarios.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        GeneraciondeHorarios.setText("Generación de Horarios");
        GeneraciondeHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneraciondeHorariosActionPerformed(evt);
            }
        });
        getContentPane().add(GeneraciondeHorarios);
        GeneraciondeHorarios.setBounds(1068, 93, 173, 25);

        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 85, 1304, 2);

        jSeparator2.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 124, 1304, 2);

        jSeparator3.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 663, 1304, 2);

        SGH.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        SGH.setText("SISTEMA DE GESTIÓN DE HORARIOS");
        getContentPane().add(SGH);
        SGH.setBounds(233, 38, 414, 29);

        LogoUnipoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.jpg"))); // NOI18N
        getContentPane().add(LogoUnipoli);
        LogoUnipoli.setBounds(685, 20, 329, 56);

        CerrarSesion.setBackground(new java.awt.Color(255, 102, 0));
        CerrarSesion.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        CerrarSesion.setText("Cerrar sesión");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(CerrarSesion);
        CerrarSesion.setBounds(1181, 51, 113, 25);

        NombredelUsuario.setText("Nombre del Usuario");
        getContentPane().add(NombredelUsuario);
        NombredelUsuario.setBounds(1056, 57, 93, 14);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("Página Principal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(555, 137, 222, 35);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(23767, 32767));
        jPanel2.setPreferredSize(new java.awt.Dimension(860, 25));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel3.setText("Universidad Politecnica de Durango, Area de Desarollo de Software");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(483, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(401, 401, 401))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 671, 1304, 23);

        AsignarMaterias.setBackground(new java.awt.Color(255, 102, 0));
        AsignarMaterias.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        AsignarMaterias.setText("Asignar Materias");
        AsignarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarMateriasActionPerformed(evt);
            }
        });
        getContentPane().add(AsignarMaterias);
        AsignarMaterias.setBounds(747, 93, 148, 25);

        AltasdeUsuarios.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        AltasdeUsuarios.setText("Altas Asignaturas");
        AltasdeUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltasdeUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(AltasdeUsuarios);
        AltasdeUsuarios.setBounds(86, 257, 170, 27);

        AsignaciondePrivilegios.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        AsignaciondePrivilegios.setText("ModificarAsignatura");
        AsignaciondePrivilegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignaciondePrivilegiosActionPerformed(evt);
            }
        });
        getContentPane().add(AsignaciondePrivilegios);
        AsignaciondePrivilegios.setBounds(86, 316, 170, 27);

        ModificaciondeUsuarios.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ModificaciondeUsuarios.setText("Eliminar Asignatura");
        ModificaciondeUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaciondeUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(ModificaciondeUsuarios);
        ModificaciondeUsuarios.setBounds(86, 376, 170, 27);

        ConsultarUsuarios.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ConsultarUsuarios.setText("Alta Cuatrimestres");
        ConsultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultarUsuarios);
        ConsultarUsuarios.setBounds(86, 439, 170, 27);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel8.setText("Usuarios");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(629, 178, 98, 17);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel9.setText(" Modificar Asignaturas");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(592, 201, 135, 17);

        AltaGuardar.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        AltaGuardar.setText("Guardar");
        AltaGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(AltaGuardar);
        AltaGuardar.setBounds(846, 522, 79, 25);

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(943, 522, 85, 25);

        tablamodificarasignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablamodificarasignaturas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 300, 631, 98);

        botonguardarcambio.setText("Modificar seleccionado");
        botonguardarcambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarcambioActionPerformed(evt);
            }
        });
        getContentPane().add(botonguardarcambio);
        botonguardarcambio.setBounds(791, 399, 237, 23);
        getContentPane().add(campoid);
        campoid.setBounds(390, 490, 93, 20);

        Id.setText("Id");
        getContentPane().add(Id);
        Id.setBounds(400, 460, 10, 14);
        getContentPane().add(nombremodificar);
        nombremodificar.setBounds(490, 490, 93, 20);

        Id1.setText("Nombre");
        getContentPane().add(Id1);
        Id1.setBounds(490, 460, 52, 14);
        getContentPane().add(creditosmodificar);
        creditosmodificar.setBounds(710, 490, 93, 20);
        getContentPane().add(clavemodificar);
        clavemodificar.setBounds(600, 490, 93, 20);
        getContentPane().add(horasmodificar);
        horasmodificar.setBounds(820, 490, 93, 20);

        Id2.setText("Clave");
        getContentPane().add(Id2);
        Id2.setBounds(600, 460, 52, 14);

        Creditos.setText("Creditos");
        getContentPane().add(Creditos);
        Creditos.setBounds(710, 460, 52, 14);

        Creditos1.setText("Horas");
        getContentPane().add(Creditos1);
        Creditos1.setBounds(820, 460, 52, 14);

        jLabel1.setText("Buscar asignatura");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(397, 403, 86, 14);

        buscarmodificarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarmodificarrActionPerformed(evt);
            }
        });
        buscarmodificarr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarmodificarrKeyPressed(evt);
            }
        });
        getContentPane().add(buscarmodificarr);
        buscarmodificarr.setBounds(493, 400, 175, 20);

        Creditos2.setText("Cuatrimestre");
        getContentPane().add(Creditos2);
        Creditos2.setBounds(930, 460, 90, 14);
        getContentPane().add(cuatrimestremodificarasignatura);
        cuatrimestremodificarasignatura.setBounds(930, 490, 93, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HorariosExternosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariosExternosActionPerformed
        // Link para modulo horarios externos
        HorariosExternos obj=new HorariosExternos();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_HorariosExternosActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        // Link para modulo usuarios
        Usuarios obj=new Usuarios();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_UsuariosActionPerformed

    private void GeneraciondeHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneraciondeHorariosActionPerformed
        // Link para modulo usuarios
        PaginaPrincipalGeneraciondeHorarios obj=new PaginaPrincipalGeneraciondeHorarios();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_GeneraciondeHorariosActionPerformed

    private void CuatrimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuatrimestreActionPerformed
        // Link para modulo cuatrimestres
        cuatrimestres obj=new cuatrimestres();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_CuatrimestreActionPerformed

    private void HorariosAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariosAlumnosActionPerformed
        // Link para modulo horarios alumnos
        HorariosAlumnos obj=new HorariosAlumnos();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_HorariosAlumnosActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        // Link para cerrar sesion
        IngresaralSistema obj=new IngresaralSistema();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void AsignarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarMateriasActionPerformed
        // Link para modulo horarios alumnos
        AsignarAsignatura obj=new AsignarAsignatura();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_AsignarMateriasActionPerformed

    private void DocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocentesActionPerformed
        // Link para modulo docentes
        Docentes obj=new Docentes();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_DocentesActionPerformed

    private void AltasdeUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltasdeUsuariosActionPerformed
        // Link para alta de asignatura
        AltasAsignaturas obj=new AltasAsignaturas();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_AltasdeUsuariosActionPerformed

    private void ConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarUsuariosActionPerformed
        // Link para dar de alta un cuatrimestre
        AltasCuatrimestre obj=new AltasCuatrimestre();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ConsultarUsuariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Solo para que refresque los datos
        mostrardatosmodificar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AsignaciondePrivilegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignaciondePrivilegiosActionPerformed
        // Link para modificar asignatura
        ModificarAsignaturas obj=new ModificarAsignaturas();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_AsignaciondePrivilegiosActionPerformed

    private void ModificaciondeUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaciondeUsuariosActionPerformed
        // Link para eliminar asignatura
        EliminarAsignaturas obj=new EliminarAsignaturas();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModificaciondeUsuariosActionPerformed

    private void botonguardarcambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarcambioActionPerformed
        // TODO add your handling code here:
        try {
        int fila= tablamodificarasignaturas.getSelectedRow();
    if(fila>=0){
        campoid.setText(tablamodificarasignaturas.getValueAt(fila, 0).toString());
        nombremodificar.setText(tablamodificarasignaturas.getValueAt(fila, 1).toString());
        clavemodificar.setText(tablamodificarasignaturas.getValueAt(fila, 2).toString());
        creditosmodificar.setText(tablamodificarasignaturas.getValueAt(fila, 3).toString());
        horasmodificar.setText(tablamodificarasignaturas.getValueAt(fila, 4).toString());
        cuatrimestremodificarasignatura.setText(tablamodificarasignaturas.getValueAt(fila, 5).toString());
        
         }
    }catch (Exception e) {
        System.out.print(e.getMessage());
        JOptionPane.showMessageDialog(rootPane,"Ingresa los datos correctamente");
        mostrardatosmodificar();   
     }    
    }//GEN-LAST:event_botonguardarcambioActionPerformed

      
    private void AltaGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaGuardarActionPerformed
       
        try {
        PreparedStatement pst;
        pst = con2.prepareStatement("UPDATE asignatura SET nombre='"+nombremodificar.getText()+"',clave='"+clavemodificar.getText()+"',creditos='"+creditosmodificar.getText()+"',horas='"+horasmodificar.getText()+"',cuatrimestreasignatura='"+cuatrimestremodificarasignatura.getText()+"' WHERE cuatrimestre_id='"+campoid.getText()+"'");
        pst.executeUpdate();
        mostrardatosmodificar();
        JOptionPane.showMessageDialog(rootPane,"Datos modificados correctamente");
        
          
        }catch (Exception e) {
        System.out.print(e.getMessage());
        JOptionPane.showMessageDialog(rootPane,"Ingrese los datos correctamente");
        mostrardatosmodificar();
        
        
    }           
                
    }//GEN-LAST:event_AltaGuardarActionPerformed

    private void buscarmodificarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarmodificarrActionPerformed
        // TODO add your handling code here:
        mostrardatosmodificar();
    }//GEN-LAST:event_buscarmodificarrActionPerformed

    private void buscarmodificarrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarmodificarrKeyPressed
        // TODO add your handling code here:
        mostrardatosmodificar();
    }//GEN-LAST:event_buscarmodificarrKeyPressed

    
    
   
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AltaGuardar;
    private javax.swing.JButton AltasdeUsuarios;
    private javax.swing.JButton AsignaciondePrivilegios;
    private javax.swing.JButton AsignarMaterias;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton ConsultarUsuarios;
    private javax.swing.JLabel Creditos;
    private javax.swing.JLabel Creditos1;
    private javax.swing.JLabel Creditos2;
    private javax.swing.JButton Cuatrimestre;
    private javax.swing.JButton Docentes;
    private javax.swing.JButton GeneraciondeHorarios;
    private javax.swing.JButton HorariosAlumnos;
    private javax.swing.JButton HorariosExternos;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Id1;
    private javax.swing.JLabel Id2;
    private javax.swing.JLabel LogoUnipoli;
    private javax.swing.JButton ModificaciondeUsuarios;
    private javax.swing.JLabel NombredelUsuario;
    private javax.swing.JLabel SGH;
    private javax.swing.JButton Usuarios;
    private javax.swing.JButton botonguardarcambio;
    public javax.swing.JTextField buscarmodificarr;
    private javax.swing.JTextField campoid;
    private javax.swing.JTextField clavemodificar;
    private javax.swing.JTextField creditosmodificar;
    private javax.swing.JTextField cuatrimestremodificarasignatura;
    private javax.swing.JTextField horasmodificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nombremodificar;
    private javax.swing.JTable tablamodificarasignaturas;
    // End of variables declaration//GEN-END:variables
   
    
        Conexion con=new Conexion();
        Connection con2=con.conexion();
        DefaultTableModel modelomodificar;
}
