/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inicio;

import Conexion_base_de_datos.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author BENJAMIN
 */
public class ModificarDisponibilidadDocentes extends javax.swing.JFrame {

    /**
     * Creates new form INTERFAZ
     */
    public ModificarDisponibilidadDocentes() {
        initComponents();
         mostrardatos();
    }
    void mostrardatos(){
       modelo = new DefaultTableModel();
        modelo.addColumn("modulo_1");
        modelo.addColumn("modulo_2");
        modelo.addColumn("modulo_3");
        modelo.addColumn("modulo_4");
        modelo.addColumn("modulo_5");
        modelo.addColumn("modulo_6");
        modelo.addColumn("modulo_7");
        modelo.addColumn("modulo_8");
        modelo.addColumn("modulo_9");
        modelo.addColumn("modulo_10");
        modelo.addColumn("modulo_11");
        modelo.addColumn("modulo_12");
        modelo.addColumn("id_docente");
        
        tablaconsultadisponibilidad.setModel(modelo);
        String []datos = new String [13];
        try{
        Statement st = con2.createStatement();
        ResultSet rs= st.executeQuery("SELECT * FROM disponibilidad");
        while (rs.next()){
        datos [0]=rs.getString(1);
        datos [1]=rs.getString(2);
        datos [2]=rs.getString(3);
        datos [3]=rs.getString(4);
        datos [4]=rs.getString(5);
        datos [5]=rs.getString(6);
        datos [6]=rs.getString(7);
        datos [7]=rs.getString(8);
        datos [8]=rs.getString(9);
        datos [9]=rs.getString(10);
        datos [10]=rs.getString(11);
        datos [11]=rs.getString(12);
        datos [12]=rs.getString(13);
       
        modelo.addRow(datos);
        tablaconsultadisponibilidad.setModel(modelo);
}
    }catch (Exception e){
       //  Logger.getLogger(consultadocentes.class.getName()).log(Level.SEVERE, null, ex); 
        System.out.println("SE HA GENERADO UN ERROR" + e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cuatrimestre = new javax.swing.JButton();
        Docentes = new javax.swing.JButton();
        HorariosExternos = new javax.swing.JButton();
        HorariosAlumnos = new javax.swing.JButton();
        Usuarios = new javax.swing.JButton();
        GeneraciondeHorarios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        SGH = new javax.swing.JLabel();
        LogoUnipoli = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        HorariosAlumnos1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        modulo6campo = new javax.swing.JCheckBox();
        modulo2campo = new javax.swing.JCheckBox();
        modulo1campo = new javax.swing.JCheckBox();
        modulo3campo = new javax.swing.JCheckBox();
        modulo4campo = new javax.swing.JCheckBox();
        modulo5campo = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        modulo7campo = new javax.swing.JCheckBox();
        modulo8campo = new javax.swing.JCheckBox();
        modulo10campo = new javax.swing.JCheckBox();
        modulo9campo = new javax.swing.JCheckBox();
        modulo11campo = new javax.swing.JCheckBox();
        modulo12campo = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsultadisponibilidad = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        Cuatrimestre.setBackground(new java.awt.Color(255, 102, 0));
        Cuatrimestre.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Cuatrimestre.setText("Cuatrimestre");
        Cuatrimestre.setAlignmentX(0.1F);
        Cuatrimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuatrimestreActionPerformed(evt);
            }
        });
        getContentPane().add(Cuatrimestre);
        Cuatrimestre.setBounds(68, 93, 111, 25);

        Docentes.setBackground(new java.awt.Color(255, 102, 0));
        Docentes.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Docentes.setText("Docentes");
        Docentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocentesActionPerformed(evt);
            }
        });
        getContentPane().add(Docentes);
        Docentes.setBounds(216, 93, 104, 25);

        HorariosExternos.setBackground(new java.awt.Color(255, 102, 0));
        HorariosExternos.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        HorariosExternos.setText("Horarios Externos");
        HorariosExternos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariosExternosActionPerformed(evt);
            }
        });
        getContentPane().add(HorariosExternos);
        HorariosExternos.setBounds(370, 93, 141, 25);

        HorariosAlumnos.setBackground(new java.awt.Color(255, 102, 0));
        HorariosAlumnos.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        HorariosAlumnos.setText("Horarios Alumnos");
        HorariosAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariosAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(HorariosAlumnos);
        HorariosAlumnos.setBounds(563, 93, 148, 25);

        Usuarios.setBackground(new java.awt.Color(255, 102, 0));
        Usuarios.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Usuarios.setText("Usuarios");
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(Usuarios);
        Usuarios.setBounds(934, 93, 93, 25);

        GeneraciondeHorarios.setBackground(new java.awt.Color(255, 102, 102));
        GeneraciondeHorarios.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        GeneraciondeHorarios.setText("Generación de Horarios");
        GeneraciondeHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneraciondeHorariosActionPerformed(evt);
            }
        });
        getContentPane().add(GeneraciondeHorarios);
        GeneraciondeHorarios.setBounds(1068, 93, 173, 25);

        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 85, 1320, 2);

        jSeparator2.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 124, 1320, 2);

        jSeparator3.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 647, 1320, 0);

        SGH.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        SGH.setText("SISTEMA DE GESTIÓN DE HORARIOS");
        getContentPane().add(SGH);
        SGH.setBounds(233, 38, 414, 29);

        LogoUnipoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.jpg"))); // NOI18N
        getContentPane().add(LogoUnipoli);
        LogoUnipoli.setBounds(685, 20, 324, 56);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton1.setText("Cerrar sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1176, 51, 113, 25);

        jLabel1.setText("Nombre del Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1051, 57, 93, 14);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("Página Principal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 137, 222, 35);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(23767, 32767));
        jPanel2.setPreferredSize(new java.awt.Dimension(860, 25));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel3.setText("Universidad Politecnica de Durango, Area de Desarollo de Software");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(506, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(394, 394, 394))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 653, 1320, 23);

        HorariosAlumnos1.setBackground(new java.awt.Color(255, 102, 0));
        HorariosAlumnos1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        HorariosAlumnos1.setText("Asignar Materias");
        HorariosAlumnos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariosAlumnos1ActionPerformed(evt);
            }
        });
        getContentPane().add(HorariosAlumnos1);
        HorariosAlumnos1.setBounds(747, 93, 148, 25);

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton2.setText("Altas de Docentes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(64, 264, 211, 27);

        jButton3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton3.setText("Baja de Docentes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(64, 308, 211, 27);

        jButton4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton4.setText("Modificar Docentes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(64, 345, 211, 27);

        jButton5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton5.setText("Consultar de Docentes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(64, 390, 211, 27);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel4.setText("Docentes");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(613, 178, 56, 17);

        jButton6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton6.setText("Alta de Disponibilidad");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(64, 435, 211, 27);

        jButton7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton7.setText("Modificar Disponibilidad");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(64, 480, 211, 27);

        jButton8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton8.setText("Bitacora de Modificaciones");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(64, 525, 211, 27);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel12.setText("Modificar Disponibilidad");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(577, 201, 160, 17);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel5.setText("Docente a Asignar Disponibilidad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 229, 199, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(310, 268, 199, 20);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel6.setText("Modulo 6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(910, 310, 53, 17);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel7.setText("Modulo 1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 310, 53, 17);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel8.setText("Modulo 2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 310, 53, 17);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel9.setText("Modulo 3");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(570, 310, 53, 17);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel10.setText("Modulo 4");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(680, 310, 53, 17);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel11.setText("Modulo 5");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(790, 310, 53, 17);
        getContentPane().add(modulo6campo);
        modulo6campo.setBounds(980, 310, 21, 21);
        getContentPane().add(modulo2campo);
        modulo2campo.setBounds(510, 310, 21, 21);
        getContentPane().add(modulo1campo);
        modulo1campo.setBounds(400, 310, 21, 21);
        getContentPane().add(modulo3campo);
        modulo3campo.setBounds(630, 310, 21, 21);
        getContentPane().add(modulo4campo);
        modulo4campo.setBounds(740, 310, 21, 21);
        getContentPane().add(modulo5campo);
        modulo5campo.setBounds(860, 310, 21, 21);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel13.setText("Modulo 7");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 350, 53, 17);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel14.setText("Modulo 8");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 350, 53, 17);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel15.setText("Modulo 9");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(570, 350, 53, 17);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel16.setText("Modulo 10");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(680, 350, 60, 17);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel17.setText("Modulo 11");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(790, 350, 60, 17);

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel18.setText("Modulo 12");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(910, 350, 60, 17);
        getContentPane().add(modulo7campo);
        modulo7campo.setBounds(400, 350, 21, 21);
        getContentPane().add(modulo8campo);
        modulo8campo.setBounds(510, 350, 21, 21);
        getContentPane().add(modulo10campo);
        modulo10campo.setBounds(740, 350, 21, 21);
        getContentPane().add(modulo9campo);
        modulo9campo.setBounds(630, 350, 21, 21);
        getContentPane().add(modulo11campo);
        modulo11campo.setBounds(860, 350, 21, 21);
        getContentPane().add(modulo12campo);
        modulo12campo.setBounds(980, 350, 21, 21);

        jButton9.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton9.setText("Cancelar");
        getContentPane().add(jButton9);
        jButton9.setBounds(880, 570, 110, 25);

        jButton10.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton10.setText("Guardar");
        getContentPane().add(jButton10);
        jButton10.setBounds(750, 570, 110, 25);

        jButton11.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jButton11.setText("Actualizar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(1010, 570, 120, 25);

        tablaconsultadisponibilidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsultadisponibilidad);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 390, 970, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HorariosExternosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariosExternosActionPerformed
        // Link para modulo horarios externos
        HorariosExternos obj=new HorariosExternos();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_HorariosExternosActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        // Link para modulo usuarios
        Usuarios obj=new Usuarios();
        obj.setVisible(true);
        dispose();


    }//GEN-LAST:event_UsuariosActionPerformed

    private void GeneraciondeHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneraciondeHorariosActionPerformed
        // Link para modulo generación de horarios
        PaginaPrincipalGeneraciondeHorarios obj=new PaginaPrincipalGeneraciondeHorarios();
        obj.setVisible(true);
        dispose();


    }//GEN-LAST:event_GeneraciondeHorariosActionPerformed

    private void CuatrimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuatrimestreActionPerformed
        // Link para modulo cuatrimestres
        cuatrimestres obj=new cuatrimestres();
        obj.setVisible(true);
        dispose();


    }//GEN-LAST:event_CuatrimestreActionPerformed

    private void HorariosAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariosAlumnosActionPerformed
        // Link para modulo horarios alumnos
        HorariosAlumnos obj=new HorariosAlumnos();
        obj.setVisible(true);
        dispose();


    }//GEN-LAST:event_HorariosAlumnosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Link para modulo cerrar sesion
        IngresaralSistema obj=new IngresaralSistema();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void HorariosAlumnos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariosAlumnos1ActionPerformed
        // Link para modulo horarios alumnos
        AsignarAsignatura obj=new AsignarAsignatura();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_HorariosAlumnos1ActionPerformed

    private void DocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocentesActionPerformed
        // Link para modulo docentes
        Docentes obj=new Docentes();
        obj.setVisible(true);
        dispose();


    }//GEN-LAST:event_DocentesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Link para modulo alta docentes
       AltadeDocentes obj=new AltadeDocentes ();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Link para consultar docente
       ConsultaDocentes obj=new ConsultaDocentes();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Link para alta disponibilidad docente
       AltaDisponibilidadDocentes obj=new AltaDisponibilidadDocentes();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 int fila= tablaconsultadisponibilidad.getSelectedRow();
    identificadorcheck= tablaconsultadisponibilidad.getValueAt(fila, 12).toString();
    if(fila>=0){
        System.out.println(tablaconsultadisponibilidad.getValueAt(fila, 0).toString().charAt(0));
        if(tablaconsultadisponibilidad.getValueAt(fila, 0).toString().charAt(0)=='0'){
            modulo1campo.setSelected(false);
            
        }else{
            modulo1campo.setSelected(true);
       }
        
         if(tablaconsultadisponibilidad.getValueAt(fila, 1).toString().charAt(0)=='0'){
            modulo2campo.setSelected(false);
            
        }else{
            modulo2campo.setSelected(true);
       }
                
        if(tablaconsultadisponibilidad.getValueAt(fila, 2).toString().charAt(0)=='0'){
            modulo3campo.setSelected(false);
            
        }else{
            modulo3campo.setSelected(true);
       }
                        
        if(tablaconsultadisponibilidad.getValueAt(fila, 3).toString().charAt(0)=='0'){
            modulo4campo.setSelected(false);
            
        }else{
            modulo4campo.setSelected(true);
       }
                                
        if(tablaconsultadisponibilidad.getValueAt(fila, 4).toString().charAt(0)=='0'){
            modulo5campo.setSelected(false);
            
        }else{
            modulo5campo.setSelected(true);
       }
                                        
        if(tablaconsultadisponibilidad.getValueAt(fila, 5).toString().charAt(0)=='0'){
            modulo6campo.setSelected(false);
            
        }else{
            modulo6campo.setSelected(true);
       }
                                                
                                                
        if(tablaconsultadisponibilidad.getValueAt(fila, 6).toString().charAt(0)=='0'){
            modulo7campo.setSelected(false);
            
        }else{
            modulo7campo.setSelected(true);
       }
                                                        
        if(tablaconsultadisponibilidad.getValueAt(fila, 7).toString().charAt(0)=='0'){
            modulo7campo.setSelected(false);
            
        }else{
            modulo7campo.setSelected(true);
       }
                                                                
                                                                
        if(tablaconsultadisponibilidad.getValueAt(fila, 7).toString().charAt(0)=='0'){
            modulo8campo.setSelected(false);
            
        }else{
            modulo8campo.setSelected(true);
       }
                                                                        
                                                                        
        if(tablaconsultadisponibilidad.getValueAt(fila, 8).toString().charAt(0)=='0'){
            modulo9campo.setSelected(false);
            
        }else{
            modulo9campo.setSelected(true);
       }
                                                                                
                                                                                
        if(tablaconsultadisponibilidad.getValueAt(fila, 9).toString().charAt(0)=='0'){
            modulo10campo.setSelected(false);
            
        }else{
            modulo10campo.setSelected(true);
       }
        
        if(tablaconsultadisponibilidad.getValueAt(fila, 10).toString().charAt(0)=='0'){
            modulo11campo.setSelected(false);
            
        }else{
            modulo11campo.setSelected(true);
       }
        
         if(tablaconsultadisponibilidad.getValueAt(fila, 11).toString().charAt(0)=='0'){
            modulo12campo.setSelected(false);
            
        }else{
            modulo12campo.setSelected(true);
       }
       /* modulo1campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 0).toString());
        modulo2campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 1).toString());
        modulo3campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 2).toString());
        modulo4campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 3).toString());
        modulo5campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 4).toString());
        modulo6campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 5).toString());
        modulo7campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 6).toString());
        modulo8campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 7).toString());
        modulo9campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 8).toString());
        modulo10campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 9).toString());
        modulo11campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 10).toString());
        modulo12campo.setText(tablaconsultadisponibilidad.getValueAt(fila, 11).toString());*/
    }
    else{
    JOptionPane.showMessageDialog(null,"no seleciono fila");
    }        // Link para modificar docentes
             // Link para modificar disponibilidad docentes
      

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Link para bitácora de modificaciones
       BitacoraDocentes obj=new BitacoraDocentes();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Link para baja de docentes
       BajaDocentes1 obj=new BajaDocentes1 ();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
 
      String[] campos= new  String[12];
        try {
     if(modulo1campo.isSelected()){
         campos[0]="1";
         
     }else{campos[0]="0";
     }
     
     
     if(modulo2campo.isSelected()){
         campos[1]="1";
         
     }else{campos[1]="0";
     }
     
     
     if(modulo3campo.isSelected()){
         campos[2]="1";
         
     }else{campos[2]="0";
     }
     
     
     if(modulo4campo.isSelected()){
         campos[3]="1";
         
     }else{campos[3]="0";
     }
     
     
     if(modulo5campo.isSelected()){
         campos[4]="1";
         
     }else{campos[4]="0";
     }
     
     
     if(modulo6campo.isSelected()){
         campos[5]="1";
         
     }else{campos[5]="0";
     }
     
     
     if(modulo7campo.isSelected()){
         campos[6]="1";
         
     }else{campos[6]="0";
     }
     
     
     if(modulo8campo.isSelected()){
         campos[7]="1";
         
     }else{campos[7]="0";
     }
     
     
     if(modulo9campo.isSelected()){
         campos[8]="1";
         
     }else{campos[8]="0";
     }
     
     
     if(modulo10campo.isSelected()){
         campos[9]="1";
         
     }else{campos[9]="0";
     }
     
     if(modulo11campo.isSelected()){
         campos[10]="1";
         
     }else{campos[10]="0";
     }
     
     if(modulo12campo.isSelected()){
         campos[11]="1";
         
     }else{campos[11]="0";
     }
     
   
        PreparedStatement pst;
        pst = con2.prepareStatement("UPDATE disponibilidad SET modulo_1='"+campos[0]+"',modulo_2='"+campos[1]+"',modulo_3='"+campos[2]+"',modulo_4='"+campos[3]+"',modulo_5='"+campos[4]+"',modulo_6='"+campos[5]+"',modulo_7='"+campos[6]+"',modulo_8='"+campos[7]+"',modulo_9='"+campos[8]+"',modulo_10='"+campos[9]+"',modulo_11='"+campos[10]+"',modulo_12='"+campos[11]+"' WHERE docente_id='"+identificadorcheck+"'");
        pst.executeUpdate();
        mostrardatos();
            } catch (Exception e) {
        System.out.print(e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cuatrimestre;
    private javax.swing.JButton Docentes;
    private javax.swing.JButton GeneraciondeHorarios;
    private javax.swing.JButton HorariosAlumnos;
    private javax.swing.JButton HorariosAlumnos1;
    private javax.swing.JButton HorariosExternos;
    private javax.swing.JLabel LogoUnipoli;
    private javax.swing.JLabel SGH;
    private javax.swing.JButton Usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox modulo10campo;
    private javax.swing.JCheckBox modulo11campo;
    private javax.swing.JCheckBox modulo12campo;
    private javax.swing.JCheckBox modulo1campo;
    private javax.swing.JCheckBox modulo2campo;
    private javax.swing.JCheckBox modulo3campo;
    private javax.swing.JCheckBox modulo4campo;
    private javax.swing.JCheckBox modulo5campo;
    private javax.swing.JCheckBox modulo6campo;
    private javax.swing.JCheckBox modulo7campo;
    private javax.swing.JCheckBox modulo8campo;
    private javax.swing.JCheckBox modulo9campo;
    private javax.swing.JTable tablaconsultadisponibilidad;
    // End of variables declaration//GEN-END:variables
private String identificadorcheck;
    Conexion con=new Conexion();
        Connection con2=con.conexion();
        DefaultTableModel modelo;

}
